import { useEffect, useState } from "react";
import { FaArrowUpRightFromSquare, FaBars, FaCodeBranch, FaGithub, FaXmark } from "react-icons/fa6";

type Project = { title: string; eyebrow: string; description: string; href: string; action: string; visual: string; tags: string[] };
const projects: Project[] = [
  { title: "Sentinel Bank", eyebrow: "Digital banking platform", description: "A secure, operations-first banking dashboard designed to make account activity, transfers, and financial oversight feel calm, clear, and trustworthy.", href: "https://sentinelbank.duckdns.org/dashboard", action: "Open dashboard", visual: "sentinel", tags: ["Fintech", "Dashboard", "Security"] },
  { title: "Agents for Human Organizations", eyebrow: "AI systems · hackathon build", description: "A thoughtful experiment in local-first AI agents: practical digital teammates that help real organizations coordinate work without losing their human center.", href: "https://agents-for-human-hackathon.vercel.app/", action: "Visit project", visual: "agents", tags: ["AI Agents", "Local-first", "Product"] },
  { title: "Customer Churn Prediction", eyebrow: "Machine learning", description: "An end-to-end predictive analytics project that identifies customers at risk of leaving, giving teams a clearer signal for timely, meaningful retention work.", href: "https://github.com/AmbroseTech/Customer-Churn-Prediction", action: "View source", visual: "churn", tags: ["Python", "Machine Learning", "Analytics"] },
  { title: "Verse Studio", eyebrow: "Generative media studio", description: "A playful creative workspace for generating video and music—built to turn a spark of an idea into rich audiovisual experiments in a few deliberate steps.", href: "https://verse-studio.duckdns.org/", action: "Enter studio", visual: "verse", tags: ["Generative AI", "Video", "Music"] },
];
const notes = [["01", "Designing software people can trust", "A few principles that guide product work where clarity and confidence matter."], ["02", "Small systems, strong foundations", "How thoughtful constraints keep ambitious projects fast and maintainable."], ["03", "The human shape of AI", "Building intelligent tools that support judgment instead of trying to replace it."]];
function Visual({ kind, title }: { kind: string; title: string }) { return <div className={`project-visual ${kind}`} role="img" aria-label={`${title} visual preview`}><span className="art-one" /><span className="art-two" /><span className="art-three" /><i /></div>; }
export default function App() {
  const [menu, setMenu] = useState(false); const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const listener = () => setScrolled(window.scrollY > 12); listener(); window.addEventListener("scroll", listener, { passive: true }); return () => window.removeEventListener("scroll", listener); }, []);
  const close = () => setMenu(false);
  return <div className="site-shell">
    <header className={`site-header ${scrolled ? "is-scrolled" : ""}`}><a className="brand" href="#top" onClick={close} aria-label="Ambrose Abaasa, home"><span className="brand-symbol">A</span><span>ambrose<span className="muted">.dev</span></span></a><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <FaXmark /> : <FaBars />}</button><nav className={menu ? "open" : ""} aria-label="Main navigation"><a href="#work" onClick={close}>Work</a><a href="#about" onClick={close}>About</a><a href="#notes" onClick={close}>Notes</a><a className="nav-github" href="https://github.com/AmbroseTech" target="_blank" rel="noreferrer"><FaGithub /> GitHub</a></nav></header>
    <main id="top"><section className="hero"><div className="hero-glow glow-one" /><div className="hero-glow glow-two" /><p className="kicker"><span /> Independent builder · Kampala, Uganda</p><h1>Making the <em>useful</em><br />feel remarkable.</h1><p className="hero-copy">I’m Ambrose—a software engineer building calm, capable products at the intersection of technology, design, and human possibility.</p><div className="hero-actions"><a className="button button-primary" href="#work">See selected work <span>↓</span></a><a className="text-link" href="https://github.com/AmbroseTech" target="_blank" rel="noreferrer">Browse all projects <FaArrowUpRightFromSquare /></a></div><div className="hero-footer"><span>SCROLL TO EXPLORE</span><span className="scroll-line" /><span>2026</span></div></section>
    <section id="work" className="section work-section"><div className="section-intro"><p className="kicker"><span /> Selected work</p><h2>Projects with a<br /><em>point of view.</em></h2><p>From reliable financial tools to playful creative systems, each project starts with a real question and ends with something people can use.</p></div><div className="project-grid">{projects.map((p, n) => <a className="project-card" href={p.href} target="_blank" rel="noreferrer" key={p.title} aria-label={`${p.action}: ${p.title}`}><Visual kind={p.visual} title={p.title} /><div className="project-content"><p className="project-count">0{n + 1}</p><p className="project-eyebrow">{p.eyebrow}</p><h3>{p.title}</h3><p className="project-description">{p.description}</p><div className="project-bottom"><div>{p.tags.map(tag => <span key={tag}>{tag}</span>)}</div><b>{p.action} <FaArrowUpRightFromSquare /></b></div></div></a>)}</div><a className="all-projects" href="https://github.com/AmbroseTech" target="_blank" rel="noreferrer"><FaCodeBranch /> Explore the full archive on GitHub <FaArrowUpRightFromSquare /></a></section>
    <section id="about" className="about-section"><div className="about-art"><span>/*</span><div className="shape shape-a" /><div className="shape shape-b" /><div className="shape shape-c" /><strong>01—26</strong></div><div className="about-copy"><p className="kicker"><span /> A little about me</p><h2>Curious by default. <em>Intentional</em> by design.</h2><p>I care about the details that turn working software into an experience: the quiet confidence of a clear interface, a system that stays fast under pressure, and an idea that becomes simpler once it is built.</p><p>My work moves between full-stack engineering, AI, data, and generative tools—always in service of something tangible.</p><a className="text-link" href="mailto:ambrosetech@gmail.com">Let’s make something <FaArrowUpRightFromSquare /></a></div></section>
    <section id="notes" className="section notes-section"><div className="notes-head"><div><p className="kicker"><span /> Field notes</p><h2>Ideas in<br /><em>progress.</em></h2></div><p>Short reflections on making technology clearer, kinder, and more useful.</p></div><div className="notes-list">{notes.map(note => <article className="note" key={note[0]}><span>{note[0]}</span><div><h3>{note[1]}</h3><p>{note[2]}</p></div><button aria-label={`Read ${note[1]}`}><FaArrowUpRightFromSquare /></button></article>)}</div></section></main>
    <footer><a className="brand" href="#top"><span className="brand-symbol">A</span><span>ambrose<span className="muted">.dev</span></span></a><p>© {new Date().getFullYear()} Ambrose Abaasa. Built with intent.</p><a href="https://github.com/AmbroseTech" target="_blank" rel="noreferrer">GitHub <FaArrowUpRightFromSquare /></a></footer>
  </div>;
}
